# Generated by Django 4.1 on 2022-10-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='location', to='shawa_base.district')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('place_type', models.SmallIntegerField(choices=[(None, 'Выберите тип шаурмичной'), (1, 'Кафе'), (2, 'Ларек'), (3, 'Фудтрак')])),
                ('phone', models.CharField(max_length=20, null=True)),
                ('delivery', models.BooleanField(default=False)),
                ('seats', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('order_by_phone', models.BooleanField(default=False)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', related_query_name='place', to='shawa_base.location')),
            ],
            options={
                'verbose_name': 'Шаурмичная',
                'verbose_name_plural': 'Шаурмичные',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='PlaceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', related_query_name='rate', to='shawa_base.place')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-creation_date'],
            },
        ),
    ]
