# Generated by Django 4.1 on 2022-10-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shawa_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='place',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Есть доставка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', related_query_name='place', to='shawa_base.location', verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='place',
            name='order_by_phone',
            field=models.BooleanField(default=False, verbose_name='Можно заказать по телефону'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Есть парковка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.SmallIntegerField(choices=[(None, 'Выберите тип шаурмичной'), (1, 'Кафе'), (2, 'Ларек'), (3, 'Фудтрак')], verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='place',
            name='seats',
            field=models.BooleanField(default=False, verbose_name='Есть столики'),
        ),
        migrations.AlterField(
            model_name='place',
            name='toilet',
            field=models.BooleanField(default=False, verbose_name='Есть туалет'),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Адрес сайта'),
        ),
    ]
