# Generated by Django 4.1 on 2022-10-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shawa_base', '0002_alter_district_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Shawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('shawa_type', models.SmallIntegerField(choices=[(None, 'Выберите тип шаурмы'), (1, 'Классическая'), (2, 'Сырная'), (3, 'Острая')], verbose_name='Тип')),
                ('meat', models.SmallIntegerField(choices=[(None, 'Выберите мясо'), (1, 'С говядиной'), (2, 'Со свининой'), (3, 'С курицей'), (4, 'С бараниной'), (5, 'Со свининой и говядиной')], verbose_name='Мясо')),
                ('size', models.SmallIntegerField(choices=[(None, 'Выберите размер'), (1, 'Огромная'), (2, 'Большая'), (3, 'Стандартная'), (4, 'Маленькая')], verbose_name='Размер')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('spicy', models.BooleanField(default=False, verbose_name='Острая')),
                ('ingredients', models.ManyToManyField(related_name='shawas', related_query_name='shawa', to='shawa_base.ingredient')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawas', related_query_name='shawa', to='shawa_base.place')),
            ],
            options={
                'verbose_name': 'Шаурма',
                'verbose_name_plural': 'Шавухи',
                'ordering': ['-creation_date'],
                'unique_together': {('place', 'shawa_type', 'meat', 'size')},
            },
        ),
    ]
